runtime: python37  # python version
entrypoint: gunicorn -b :$PORT main:app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
  target_throughput_utilization: 0.5

instance_class: F2

env_variables:
  SECRET_KEY: "966511fc2c78542e0e09d76c9012d3a7"  # your secret key
